config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sales#index'
  get "about", to: "sales#about"
  get "weekly-reports", to: "sales#weekly"
  get "monthly-reports", to: "sales#monthly"
  get "prediction", to: "sales#prediction"
  get "displayprediction", to: "sales#displayprediction"
  resources :sales, only: %i[new create edit update] do 
    collection { post :import} 
  end
  resources :products, only: %i[index new create edit update] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :sale_items

	def self.to_csv 
		CSV.generate do |csv|
			csv << column_names
			all.each do |sales|
				csv << sales.attributes.values_at(*column_names)
			end
		end
	end
end

app/models/sale.rb
class Sale < ApplicationRecord
	has_many :sale_items
	has_many :products, through: :sale_items

	#CSV.foreach(file.path, headers: true) do |row|
	#	sales.create! row.to_hash 
	#end

	def total_price
  		sale_items.sum { |item| (item.product.price * item.quantity) }
	end

	def money_format(cents)
		sprintf('%.2f', (cents/100).to_f)
	end

	def self.to_csv 
		attributes = %w{name stock price active created_at updated_at}

		CSV.generate(headers: true) do |csv|
			csv << attributes
			all.each do |products|
				csv << attributes.map{ |attr| products.send(attr) }
			end
		end
	end

	def self.to_csv1 
		attributes = %w{id saleTime dollars sale_items}

		CSV.generate(headers: true) do |csv|
			csv << attributes
			all.each do |sale|
				data = []
				array = []
				data << sale.id
				data << sale.saleTime
				total = 0
				sale.sale_items.each do |si|
					array << "product name = #{si.product.name}, quantity = #{si.quantity}, price = #{si.product.price/100}"
					total += (si.product.price * si.quantity)
				end
				data << total/100
				data << array
				csv << data
			end
		end
	end
end

app/models/sale_item.rb
class SaleItem < ApplicationRecord
  belongs_to :sale
  belongs_to :product

  def total_cents
    product.price * quantity
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.where("active = true")
		respond_to do |format|
			format.html
			format.csv { render text: @products/index.to_csv }
	end
end

	def create
		price = product_params[:price]
	    @product = Product.new(product_params)
	    @product.active = true
	    price = (price.to_f * 100).to_i
	    @product.price = price
	    if @product.save
	      redirect_to products_path
	    else
	      render :new
	    end
	end

	def new
	end

	def edit
		@product = Product.find(params[:id])
		@product.price = sprintf('%.2f', (@product.price/100).to_f)
	end

	def update
		@product = Product.find(params[:id])
		h = product_params.to_h
		price = h[:price]
		price = (price.to_f * 100).to_i
		h[:price] = price
		puts h
		if @product.update(h)
	      redirect_to products_path
	    else
	      render :edit
	    end
	end

	private

    def product_params
    	params.require(:product).permit(:name, :stock, :price, :active)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
	def index
		if params[:query].present?
      		sql_query = "name LIKE :query OR saleTime LIKE :query"
    		@sales = Sale.joins(:sale_items, :products).where(sql_query, query: "%#{params[:query]}%").distinct
    		@products = Product.all
			respond_to do |format|
				format.html
				format.csv { send_data @products.to_csv, filename: "products-#{Date.today}.csv" }
			end
    	else
			@sales = Sale.all
			@products = Product.all
			respond_to do |format|
				format.html
				format.csv { send_data @products.to_csv, filename: "products-#{Date.today}.csv" }
			end
		end
	end
	
	def import 
		sales.import(params[:file])	
		redirect_to sales_path, notice: "uploaded successfully" 
	end

	def about
	end

	def new
	end

	#Still Needs Work
	def create
		error = ""
		products = params[:sales][:products]
		puts(products)
		sale = Sale.new(saleTime: Time.now())
		products.each do |p|
			product = Product.find(p["id"])
			quant = p["quantity"].to_i
			if quant <= product.stock
				product.stock = product.stock - quant
				si = SaleItem.new
				si.product = product
				si.quantity = quant
				si.sale = sale
				si.save()
				product.save()
			else
				error = "not enough stock"
				puts error
			end
		end
		if (error == "")

			if sale.save
				sale.sale_items.each do |si| 
					si.product.save
					puts " PRODUCT STOKK #{si.product.stock}"
					si.save
				end
				redirect_to root_path
			else
				raise ActiveRecord::Rollback, "Could not save! #{error}"
			end
		else
			raise ActiveRecord::Rollback, "Could not save! #{error}"
			error = ""
			render :new
		end
	end

	def edit
		@sale = Sale.find(params[:id])
	end

	def update
	end

	def weekly
		week_ago = Time.now() - 7.days
		@sales = Sale.where(saleTime: (week_ago)..Time.now)
		@items = []
		@sales.each do |sale|
			sale.sale_items.each do |item|
				@items << item
			end
		end
		respond_to do |format|
			format.html
			format.csv { send_data @sales.to_csv1, filename: "weekly-#{Date.today}.csv" }
		end

		@total_products_sold = {}
		@sales.each do |sale|
			sale.sale_items.each do |item|
				k = item.product
				value = item.quantity.to_i. + (@total_products_sold[k].to_i)
				@total_products_sold[k] = value
			end
		end

	    @week_revenue = 0
		@total_products_sold.each do |k, v|
			@week_revenue = @week_revenue + (k.price * v)
		end
	end

	def monthly
		month_ago = Time.now() - 1.month
		@sales = Sale.where(saleTime: (month_ago)..Time.now)
		respond_to do |format|
			format.html
			format.csv { send_data @sales.to_csv1, filename: "monthly-#{Date.today}.csv" }
		end

		@total_products_sold = {}
		@sales.each do |sale|
			sale.sale_items.each do |item|
				k = item.product
				value = item.quantity.to_i. + (@total_products_sold[k].to_i)
				@total_products_sold[k] = value
			end
		end

		@month_revenue = 0
		@total_products_sold.each do |k, v|
			@month_revenue = @month_revenue + (k.price * v)
		end
	end	

	def destroy
		@sale = Sale.find(params[:id])
		@sale.delete

		redirect_to root_path
    end

	def prediction
		@products = Product.all
		#to keep flash message after redirect_to display flash message
		flash.keep
		#when search is done
		if params[:search]
			#entered id by user
			@search_term = params[:search]
			#sales from now to last month
			@saleitemsm1 = SaleItem.where(product_id: @search_term, created_at: (Time.now-1.month)..Time.now)
			#sales between 1 month ago to 2 months ago
			@saleitemsm2 = SaleItem.where(product_id: @search_term, created_at: (Time.now-2.month)..Time.now-1.month)
			
			#final predicted value initialised
			@predicted_value = 0
			if(SaleItem.where(product_id: @search_term).present?)

				# check if sale data 1 exists
				if @saleitemsm1.present?
					@saleitemsm1.each do |s|
						@predicted_value += s.quantity
					end
				end
				#check if sale data 2 exists
				if @saleitemsm2.present?
					@saleitemsm2.each do |s|
						@predicted_value += s.quantity
					end
					@predicted_value /=2
				end
				
				if(@predicted_value == 0)
					display = "There is not enough data to predict sales of this item."
				else
				display = "The next months prediction for the item with id #{@search_term} is #{@predicted_value} units."
				end
			else
				display = "There is no item in the database with that id."
			end
			redirect_to displayprediction_path, :flash => { :notice => display}
			
		end
	end

	private

	def set_sale
    	@sales = Sale.find(params[:id])
    end

	def sale_items_params
		params.permit(:product_id, :quantity)
	end

    def sale_params
    	params.require(:sale).permit(:saleTime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhpSalesRecordManagment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  
  <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<div class="container">
	<h1>Edit Product <%= "ID:#{@product.id} #{@product_name}" %></h1>

	<%= form_with model: @product do |form| %>
	  <div>
	    <%= form.label :name %><br>
	    <%= form.text_field :name %>
	  </div>

	  <div>
	    <%= form.label :stock %><br>
	    <%= form.text_field :stock %>
	  </div>

	  <div>
	    <%= form.label :price %><br>
	    <%= form.text_field :price %>
	  </div>

	  <div>
	    <%= form.label :active %><br>
	    <%= form.check_box :active %>
	  </div>

	  <div>
	    <%= form.submit %>
	  </div>
	<% end %>
</div>

app/views/products/index.html.erb
<div class="container">
	<h1>PhpSalesRecordManagment Products</h1>

	<% @products.each do |prod| %>

		<div class="sales-container">

			<%= link_to "Edit", edit_product_path(prod) %>
			<h2>ID: <%= prod.id %><br><%= prod.name %></h2>

			<div class="product-info">
				<p>$<%= sprintf('%.2f', (prod.price/100).to_f) %>/unit</p>
				<p>Stock: <%= prod.stock %> units</p>		
			</div>

			<div>
				<% if prod.stock <= 10 %>
				<p style ="color: #ff0000"> <strong> <%= prod.name %> stock is running low </strong></p>
				<% end %>

			</div>

			<%= link_to "Destroy", product_path(prod),
				method: :delete,
        data: { confirm: "Delete this product?" } %>
			</div>	

	<% end %>
</div>

app/views/products/new.html.erb
<div class="container">
	<h1>New Product</h1>

	<%= form_with model: @product, url:products_path, scope: :product do |form| %>
	  <div>
	    <%= form.label :name %><br>
	    <%= form.text_field :name %>
	  </div>

	  <div>
	    <%= form.label :stock %><br>
	    <%= form.text_field :stock %>
	  </div>

	  <div>
	    <%= form.label :price %><br>
	    <%= form.text_field :price %>
	  </div>

	  <div>
	    <%= form.submit %>
	  </div>
	<% end %>
</div>

app/views/sales/_form.html.erb
<br>
<%= form.select("products[]id", Product.all.collect{|p| ["#{p.name} $#{sprintf('%.2f', (p.price/100).to_f)}", p.id]}) %>
<%= form.text_field "products[]quantity" %>
<br>
<br>

app/views/sales/about.html.erb
<div class="container">
    <h1 class="aboutPage">About page<h1>
    <p class="aboutPage">For any queries, please feel free to contact any of the devs!<p>
        <P><a href = "mailto: 102267153@student.swin.edu.au">Send Email to Agrim</a></P>
        <P><a href = "mailto: 103077133@student.swin.edu.au">Send Email to Benjamin D</a></P>
        <P><a href = "mailto: 103060667@student.swin.edu.au">Send Email to Benjamin S</a></P>
        <P><a href = "mailto: 103168804@student.swin.edu.au">Send Email to Etienne</a></P>
        <P><a href = "mailto: 103615999@student.swin.edu.au">Send Email to Thomas</a></P>
</div>

app/views/sales/displayprediction.html.erb
<div class="container">
	<h1>PhpSalesRecordManagment Monthly Prediction</h1>
<p><%= flash[:notice] %></p>
</div>

app/views/sales/edit.html.erb
<div class="container">
	<h1>New Sale</h1>

	<%= form_with model: @sale, url: sales_path, scope: :sales do |form|  %>
		<div>
			<%= form.label :product_id1, "Product ID #1" %><br>
			<%= form.select(:product_ids, Product.all.collect {|p| [ p.name, p.id ] }) %><br>
			<%= form.label :quantity1 %><br>
			<input id="quantity1" name="quantity1" type="text_field"></input></br>
			<br>
			<%= form.label :product_id2, "Product ID #2" %><br>
			<input id="product_id2" name="product_id2" type="text_field"></input></br>
			<%= form.label :quantity2 %><br>
			<input id="quantity2" name="quantity2" type="text_field"></input></br>
		</div>
		<br>

		<div>
			<%= form.submit %>
		</div>

	<% end %>
</div>

app/views/sales/index.html.erb
<div class="container">
	<h1>PhpSalesRecordManagment Sales</h1>
	<p>Search Sales</p>
	<!-- SEARCH BAR -->
	<div class="">
	  <div class="">
	    <div class=""></div>
	    <input size="40" type="text" placeholder="Search product or time (YYYY-MM-DD)" confirm-type="search" id="search"></input>
	  </div>
	  <br>
	  <div class="button-container">
	    <div class="btn btn-default" id="searchButton">Search</div>
	  </div>
	  <br>
	</div>
	<%= link_to "Add Sale", new_sale_path, class: "btn" %>
	<% @sales.each do |sale| %>
		<div class="sales-container">
			<%= link_to "Edit", edit_sale_path(sale) %>
			<h2>ID:<%= sale.id %> Sale at <%= sale.saleTime %></h2>
			<div class="sales-info">
				<% sale.sale_items.each_with_index do |si, ind| %>
					<h3><%= "Item #{ind + 1}: #{si.product.name}" %></h3>
					<p><%= si.quantity %> at $<%= sprintf('%.2f', (si.product.price/100).to_f) %> = $<%= sprintf('%.2f', (si.total_cents).to_f/100) %></p>
				<% end %>
				<h2>$<%= sprintf('%.2f', (sale.total_price).to_f/100) %></h2>
			</div>
		</div>
	<% end %>
</div>

<div class="download-button">
<h3>Download CSV</h3>
<%= link_to "download", root_path(format: "csv"), class: 'btn btn-default' %>

</div>

app/views/sales/monthly.html.erb
<div class="container">
	<h1>PhpSalesRecordManagment Monthly Report</h1>
	<p>This month's revenue: $<%= sprintf('%.2f', @month_revenue/100.to_f) %></p>
	<p>This month we have sold:</p>
	<% @total_products_sold.each do |k, v| %>
		<p>Name:<%= k.name %> - quantity <%= v %> - Revenue <%= sprintf('%.2f', (k.price * v/100).to_f) %> Remaining - <%= k.stock %></p>
	<% end %>
	<% @sales.each do |sale| %>
		<div class="sales-container">
			<h2>ID:<%= sale.id %> Sale at <%= sale.saleTime %></h2>
			<div class="sales-info">
				<% sale.sale_items.each_with_index do |si, ind| %>
					<h3><%= "Item #{ind + 1}: #{si.product.name}" %></h3>
					<p><%= si.quantity %> at $<%= sprintf('%.2f', (si.product.price/100).to_f) %> = $<%= sprintf('%.2f', (si.total_cents).to_f/100) %></p>
				<% end %>
				<h2>$<%= sprintf('%.2f', (sale.total_price).to_f/100) %></h2>
			</div>
		</div>
	<% end %>
</div>

<div class="download-button">
<h3>Download CSV</h3>
<%= link_to "download", monthly_reports_path(format: "csv"), class: 'btn btn-default' %>

</div>

app/views/sales/monthlyprediction.erb
<head>
</head>
<div class="container">
<h1>PhpSalesRecordManagment Monthly Prediction</h1>
<p>Enter the item id to see its next months predicted sale</p>

<%= form_with model: @sale, url:monthly_prediction_path, scope: :sale do |form| %>
    <%= form.text_field :searchid %>
    <div>
    <%= form.label :searchid, "Enter the id of the product:" %><br>
    </div>
    
    <div>
    <%= form.submit "Predict sales" %>
	</div>
    <div name="poponsubmit">
    <p></p>
    </div>
    <% end %>
    </div>
    <%= javascript_pack_tag 'monthlyprediction'%>

app/views/sales/new.html.erb
<div class="container">
	<h1>New Sale</h1>

	<%= form_with model: @sale, url: sales_path, scope: :sales do |form|  %>
		<div id="adding-products">
			<p>Select a Product</p>
			<div id="form-container">
				<div id="form"><%= render partial: "sales/form", locals: { form: form } %></div>
			</div>
			<div id="addProd" class="btn">Add Product</div>
		</div>
		<br>
		<div>
			<%= form.submit %>
		</div>

	<% end %>
</div>

app/views/sales/newProduct.html.erb
<h1>New Product</h1>

<%= form_with model: @products do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :stock %><br>
    <%= form.text_field :stock %>
  </div>
  
  <div>
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>
  
  <div>
    <%= form.label :active %><br>
    <%= form.check_box :active %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sales/prediction.html.erb
<head>
</head>
<div class="container">
<h1>PhpSalesRecordManagment Monthly Prediction</h1>


<p>Enter the id of the product whose next months sale prediction is desired:</p>
<% @products.each do |product| %>
    <p><span><%= product.id %>.</span>  <span><%= product.name %></span></p>
<% end %>
<p>(for example, 2,3,4)</p>
    <%= form_for "", url: prediction_path, role: "search", method: :get do%>
        <%= text_field_tag :search , @search_term, placeholder: "Search by id"%>
        
    <% end %>

app/views/sales/weekly.html.erb
<div class="container">
	<h1>PhpSalesRecordManagment Weekly Report</h1>
	<p>This week's revenue: $<%= sprintf('%.2f', @week_revenue/100.to_f) %></p>
	<p>This week we have sold:</p>
	<% @total_products_sold.each do |k, v| %>
		<p>Name:<%= k.name %> - quantity <%= v %> - Revenue <%= sprintf('%.2f', (k.price * v/100).to_f) %> Remaining - <%= k.stock %></p>
	<% end %>
	<% @sales.each do |sale| %>
		<div class="sales-container">
			<h2>ID:<%= sale.id %> Sale at <%= sale.saleTime %></h2>
			<div class="sales-info">
				<% sale.sale_items.each_with_index do |si, ind| %>
					<h3><%= "Item #{ind + 1}: #{si.product.name}" %></h3>
					<p><%= si.quantity %> at $<%= sprintf('%.2f', (si.product.price/100).to_f) %> = $<%= sprintf('%.2f', (si.total_cents).to_f/100) %></p>
				<% end %>
				<h2>$<%= sprintf('%.2f', (sale.total_price).to_f/100) %></h2>
			</div>
		</div>
	<% end %>
</div>

<div class="download-button">
<h3>Download CSV</h3>
<%= link_to "download", weekly_reports_path(format: "csv"), class: 'btn btn-default' %>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="container">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li><%= link_to "Sales", root_path, class:"nav-link" %></li>
        <li><%= link_to "Add Sale", new_sale_path, class:"nav-link" %></li>
        <li><%= link_to "Products", products_path, class:"nav-link" %></li>
        <li><%= link_to "Add Product", new_product_path, class:"nav-link" %></li>
        <li><%= link_to "About", about_path, class:"nav-link" %></li>
        <li><%= link_to "Weekly Reports", weekly_reports_path, class:"nav-link" %></li>
        <li><%= link_to "Monthly Reports", monthly_reports_path, class:"nav-link" %></li>
        <li><%= link_to "Prediction", prediction_path, class:"nav-link" %></li>
      </ul>
    </div>
  </div>
</nav>